{
 "title": "Data Monitoring Compressor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Variables_List",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.measurements(bucket: \"${Bucket}\")"
   },
   { "name": "Bucket", "query": "buckets()" }
  ]
 },
 "panels": [
  { "title": "Individual Variable Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${Variables_List} Real Values vs Prediction",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "${Variables_List} (last 5 values)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n"
    }
   ]
  },
  {
   "title": "${Variables_List} (last 5 predictions)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n"
    }
   ]
  },
  {
   "title": "${Variables_List} (last 5 errors)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Error\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n"
    }
   ]
  },
  { "title": "${Variables_List} Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 11, "y": 8 } },
  {
   "title": "${Variables_List} (last values)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 1, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -2m)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n  |> last()"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -2m)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n  |> last()"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -2m)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Error\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${Variables_List}\")\r\n  |> last()"
    }
   ]
  },
  { "title": "Quick view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "C_phi_L3 monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"C_phi_L3\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"C_phi_L3\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "F monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"F\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"Compressor_Data\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"F\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "H_TDH_I_L3_N monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"H_TDH_I_L3_N\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"H_TDH_I_L3_N\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "H_TDH_U_L2_N monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"H_TDH_U_L2_N\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"H_TDH_U_L2_N\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "I_SUM monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"I_SUM\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"I_SUM\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "P_SUM monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P_SUM\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"P_SUM\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ReacEc_L1 monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReacEc_L1\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReacEc_L1\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "ReacEc_L3 monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "voltampreact" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReacEc_L3\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ReacEc_L3\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "RealE_SUM monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RealE_SUM\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RealE_SUM\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "U_L1_N monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"U_L1_N\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"U_L1_N\")\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Last 5 values for each variable",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Real Data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"C_phi_L3\" or r[\"_measurement\"] == \"F\" or r[\"_measurement\"] == \"H_TDH_I_L3_N\" or r[\"_measurement\"] == \"H_TDH_U_L2_N\" or r[\"_measurement\"] == \"I_SUM\" or r[\"_measurement\"] == \"P_SUM\" or r[\"_measurement\"] == \"ReacEc_L1\" or r[\"_measurement\"] == \"ReacEc_L3\" or r[\"_measurement\"] == \"RealE_SUM\" or r[\"_measurement\"] == \"U_L1_N\")\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Last 5 Predictions for each variable",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Prediction Data\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"C_phi_L3\" or r[\"_measurement\"] == \"F\" or r[\"_measurement\"] == \"H_TDH_I_L3_N\" or r[\"_measurement\"] == \"H_TDH_U_L2_N\" or r[\"_measurement\"] == \"I_SUM\" or r[\"_measurement\"] == \"P_SUM\" or r[\"_measurement\"] == \"ReacEc_L1\" or r[\"_measurement\"] == \"ReacEc_L3\" or r[\"_measurement\"] == \"RealE_SUM\" or r[\"_measurement\"] == \"U_L1_N\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Last 5 \"Errors\" for each variable",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${Bucket}\")\r\n  |> range(start: -1h)\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> limit(n: 5)\r\n  |> filter(fn: (r) => r[\"DataType\"] == \"Error\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"C_phi_L3\" or r[\"_measurement\"] == \"F\" or r[\"_measurement\"] == \"H_TDH_I_L3_N\" or r[\"_measurement\"] == \"H_TDH_U_L2_N\" or r[\"_measurement\"] == \"I_SUM\" or r[\"_measurement\"] == \"P_SUM\" or r[\"_measurement\"] == \"ReacEc_L1\" or r[\"_measurement\"] == \"ReacEc_L3\" or r[\"_measurement\"] == \"RealE_SUM\" or r[\"_measurement\"] == \"U_L1_N\")\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  { "title": "C_phi_L3 Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 45 } },
  { "title": "F Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 8, "y": 45 } },
  { "title": "H_TDH_I_L3_N Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 45 } },
  { "title": "H_TDH_U_L2_N Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 } },
  { "title": "I_SUM Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 } },
  { "title": "P_SUM Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 } },
  { "title": "ReacEc_L1 Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 } },
  { "title": "ReacEc_L3 Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 } },
  { "title": "RealE_SUM Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 } },
  { "title": "U_L1_N Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 } }
 ]
}